feat: APIドキュメントを追加
Growthers/Oshavery pull request #21
Opened 2021-12-28 08:32 UTC by laminne

- 現在仕様がわかっているAPIドキュメントを追加
- 開発ドキュメントを追加
((間違えて直接レポジトリにコミットしたのは許してくれ)

2021-12-28 14:20 UTC, Sigumaa approved these changes

2021-12-29 12:29 UTC, YukiYuigishi requested changes

2021-12-29 12:29 UTC, laminne commented on docs/API/v01/server-info.md
> +  "tos": "https://example.com/tos",
利用規約の英語の略です

2021-12-29 12:40 UTC, YukiYuigishi approved these changes

2021-12-29 12:40 UTC, merged